# Generated by Django 5.1.3 on 2024-11-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialoghistory',
            name='dialog_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
